### ISSUE TITLE
Update AppVeyor config

### ISSUE THREAD

**Issue by vweevers** [ironSource/node-generator-nom#15]
Remove:

`npm -g i npm@latest`

Add:

```yaml
platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
```
